framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

 # cache configuration
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            #Prototype
            bileMo_cache:
                adapter: cache.adapter.redis
                provider: cache.default_redis_provider

sensio_framework_extra:
    router:
        annotations: false
