version: 2
jobs:
    phpunit:
        docker:
            - environment:
                BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
                DB_HOST: '${DB_HOST}'
                DB_DRIVER_DEV: '${DB_DRIVER_DEV}'
                DB_CHARSET_DEV: '${DB_CHARSET_DEV}'
                DB_VERSION_DEV: '${DB_VERSION_DEV}'
                DATABASE_URL_DEV: '${DATABASE_URL_DEV}'
            - image: circleci/php:7.2.9-apache-browsers
        steps:
            - checkout
            - run: echo 'Hello World'
            - run: sudo apt install -y libsqlite3-dev zlib1g-dev
            - run: sudo docker-php-ext-install zip
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor
            - run: ./bin/console d:d:c --env=test
            - run: ./bin/console d:s:c --env=test
            - run: ./bin/console d:f:l --env=test -n
            - run: ./bin/phpunit -v --exclude-group Blackfire
workflows:
    version: 2
    unit_test:
        jobs:
            - phpunit
