App\Domain\Models\Users:
    properties:
        username:
            - NotBlank:
            - Length:
                min: 6
                minMessage : 'Le pseudo doit contenir au moins 6 caractères'
                groups: ['user']

        password:
            - NotBlank:
            - Length:
                min: 8
                max: 50
                minMessage : 'Le mot de passe doit contenir au moins 8 caractères'
                groups: ['user']
#
        firstName:
            - NotBlank:
            - Length:
                min: 2
                minMessage : 'Le prénom doit contenir au moins 2 caractères'
                groups: ['user']
#
        lastName:
            - NotBlank:
            - Length:
                min: 2
                minMessage: 'Le Nom de famille doit contenir au moins 2 caractères'
                groups: ['user']
        mail:
            - NotBlank:
            - Email:
                mode: loose
                message: 'Addresse mail non valide'
                groups: ['user']
        phone:
            - Regex:
                pattern: '/^[0-9]{2}.[0-9]{2}.[0-9]{2}.[0-9]{2}/'
                match: true
                message: 'Le numero de téléphone doit être de la forme XX.XX.XX.XX.XX'
                groups: ['user']
