doctrine:
    orm:
        metadata_cache_driver:
            type: redis
            host: '%env(DB_HOST)%'
            port: '%env(REDIS_PORT)%'
        query_cache_driver:
            type: redis
            host: '%env(DB_HOST)%'
            port: '%env(REDIS_PORT)%'
        result_cache_driver:
            type: redis
            host: '%env(DB_HOST)%'
            port: '%env(REDIS_PORT)%'
